version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - app-db:/app/instance  
      - app-temp:/app/temp    
    depends_on:
      - redis

  celery-worker:
    build: ./app
    command: celery -A app.tareas.tareas worker -l info
    volumes:
      - app-db:/app/instance
      - app-temp:/app/temp
    depends_on:
      - redis
    environment:
      - C_FORCE_ROOT=true

  # redis_app:
  #   build: ./redis_app
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - app-db:/app/instance  # Mount the same volume for the SQLite database
  #     - app-temp:/app/temp     # Mount the same volume for the Temp folder
  #   depends_on:
  #     - app

volumes:
  app-db:  # Define a named volume for the SQLite database
  app-temp:  # Define a named volume for the Temp folder