version: "3"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  pgsql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  celery-worker:
    build: ./app
    command: celery -A app.celery worker -l info
    volumes:
      - app-db:/app/instance
      - app-temp:/app/temp
    depends_on:
      - redis
      - pgsql
    environment:
      - C_FORCE_ROOT=true

  app:
    build: ./app
    command: python app.py
    ports:
      - "5000:5000"
    environment:
      - DB_URL=postgresql://postgres:postgres@psql:5432/postgres
    volumes:
      - app-db:/app/instance  
      - app-temp:/app/temp    
    depends_on:
      - redis
      - pgsql

  # convert:
  #   build: ./convertion_app
  #   command: python app.py
  #   ports:
  #     - "5000:5001"
  #   environment:
  #     - DB_URL=postgresql://postgres:postgres@psql:5432/postgres
  #   volumes:
  #     - app-db:/app/instance  
  #     - app-temp:/app/temp    
  #   depends_on:
  #     - redis
  #     - pgsql
  #     - app


volumes:
  app-db:  # Define a named volume for the SQLite database
  app-temp:  # Define a named volume for the Temp folder