# Use the official Python image as your base image
FROM python:3.10-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy your application code and requirements file into the container
COPY requirements.txt requirements.txt
COPY . .

# Install the required Python packages
RUN pip3 install -r requirements.txt

# Create a directory for temporary files
RUN mkdir /app/temp

# Install FFmpeg from Alpine Linux testing repository
RUN apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing ffmpeg

# Install Redis
RUN apk add --no-cache redis
