# Use the official Python image as your base image
FROM python:3.10-alpine
 
# Set the working directory inside the container
WORKDIR /app
 
# Copy your application code and requirements file into the container
COPY requirements.txt requirements.txt
COPY . .
 
# Install the required Python packages
RUN pip3 install -r requirements.txt
 
RUN pip install gunicorn
 
CMD exec gunicorn --bind :8080 --workers 1 --threads 0 --timeout 0 app:app
 
# Create a directory for temporary files
RUN mkdir /app/temp
 
 
ENV FLASK_APP=app.py
# watch app' files
ENV FLASK_DEBUG=true
ENV FLASK_ENV=development