# Use the official Python image as your base image
FROM python:3.10-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy your application code and requirements file into the container
COPY requirements.txt requirements.txt
COPY . .

# Install the required Python packages
RUN pip3 install -r requirements.txt

ENV FLASK_APP=app.py
# watch app' files
ENV FLASK_DEBUG=true
ENV FLASK_ENV=development

# Run the web service on container startup
CMD ["flask", "run"]