# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory to /app
WORKDIR /conversion_app

# Copy the current directory contents into the container at /app
COPY . /conversion_app

# Install FFmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World
